# Generated by Django 3.1.7 on 2022-09-27 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20220211_1227'),
        ('posts', '0009_auto_20220927_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='variant',
            new_name='content',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='users',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
